[‎9/‎28/‎2016 1:41 PM] Zhang, Shanlong:
db:
  scale: 1
wordPressLB:
  scale: 3
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
wordpress:
  scale: 1
