db:
  scale: 1
wordPressLB:
  scale: ${wordpress_num}
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
wordpress:
  scale: 1
.catalog:
  name: "Wordpress"
  version: "v0.1-emc4ever"
  description: "Blog tool, publishing platform and CMS"
  questions:    
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: wordpress_num
      description: "Number of wordpress instance"
      label: "Number of wordpress instance"
      required: true
      default: "1"
      type: "init"
    - variable: mysql_data
      description: "Name of volume from rexray for /var/lib/mysql"
      lable: "Name of volume from rexray"
      required: true
      default: "mysql1"
      type: "string"
